[package]
name = "util"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
reqwest = "0.11"
rand = "0.8"
tokio.workspace = true
choices = { path = "../", features = ["json"] }
